# Generated by Django 5.0.4 on 2024-05-24 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_alter_genre_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='biography',
            field=models.CharField(blank=True, max_length=2000),
        ),
        migrations.AddField(
            model_name='person',
            name='poster_path',
            field=models.URLField(blank=True, null=True),
        ),
    ]
